<?= $this->doctype() ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?= $this->headTitle('ZF3 na prática')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])

        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('dist/css/skins/_all-skins.min.css'))
        ->prependStylesheet($this->basePath('dist/css/AdminLTE.min.css'))
        ->prependStylesheet($this->basePath('css/ionicons.min.css'))
        ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>




    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">

    <header class="main-header">
        <!-- Logo -->
        <a href="dashboard.html" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>ZF3</b></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>ZF3</b> ná prática</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">

                    <!-- User Account: style can be found in dropdown.less -->
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="dist/img/user2-160x160.jpg" class="user-image" alt="User Imag">
                            <span class="hidden-xs"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">

                                <p>
                                    Alexander Pierce
                                </p>
                            </li>

                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-right">
                                    <a href="login.html" class="btn btn-default btn-flat">Sign out</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <!-- =============================================== -->

    <!-- Left side column. contains the sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">

            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="header">MAIN NAVIGATION</li>

                <li>
                    <a href="dashboard.html">
                        <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                    </a>
                </li>

                <li>
                    <a href="plus.html">
                        <i class="fa fa-plus"></i> <span>Novo Ticket</span>
                    </a>
                </li>

            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- =============================================== -->

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <?= $this->content ?>

    </div>
    <!-- /.content-wrapper -->

<!--    <footer class="main-footer">-->
<!--        <div class="pull-right hidden-xs">-->
<!--            <b>Version</b> 2.4.0-->
<!--        </div>-->
<!--        <strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights-->
<!--        reserved.-->
<!--    </footer>-->
</div>
<!-- ./wrapper -->

<!-- Scripts -->
<?= $this->headScript()
    ->prependFile($this->basePath('dist/js/adminlte.min.js'))
    ->prependFile($this->basePath('js/fastclick/lib/fastclick.js'))
    ->prependFile($this->basePath('js/jquery-slimscroll/jquery.slimscroll.min.js'))
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery.min.js'))
?>

<?= $this->inlineScript() ?>
</body>
</html>









<!---->
<!---->
<!---->
<!---->
<!--<html lang="en">-->
<!--    <head>-->
<!--        <meta charset="utf-8">-->
<!--        --><?//= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>
<!---->
<!--        --><?//= $this->headMeta()
//            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
//            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
//        ?>
<!---->
<!--        <!-- Le styles -->-->
<!--        --><?//= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
//            ->prependStylesheet($this->basePath('css/style.css'))
//            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
//            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
//        ?>
<!---->
<!--        <!-- Scripts -->-->
<!--        --><?//= $this->headScript()
//            ->prependFile($this->basePath('js/bootstrap.min.js'))
//            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
//        ?>
<!--    </head>-->
<!--    <body>-->
<!--        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">-->
<!--            <div class="container">-->
<!--                <div class="navbar-header">-->
<!--                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">-->
<!--                        <span class="icon-bar"></span>-->
<!--                        <span class="icon-bar"></span>-->
<!--                        <span class="icon-bar"></span>-->
<!--                    </button>-->
<!--                    <a class="navbar-brand" href="--><?//= $this->url('home') ?><!--">-->
<!--                        <img src="--><?//= $this->basePath('img/zf-logo-mark.svg') ?><!--" height="28" alt="Zend Framework --><?//= \Application\Module::VERSION ?><!--"/>&nbsp;Skeleton Application-->
<!--                    </a>-->
<!--                </div>-->
<!--                <div class="collapse navbar-collapse">-->
<!--                    <ul class="nav navbar-nav">-->
<!--                        <li class="active"><a href="--><?//= $this->url('home') ?><!--">Home</a></li>-->
<!--                    </ul>-->
<!--                </div>-->
<!--            </div>-->
<!--        </nav>-->
<!--        <div class="container">-->
<!--            --><?//= $this->content ?>
<!--            <hr>-->
<!--            <footer>-->
<!--                <p>&copy; 2005 - --><?//= date('Y') ?><!-- by Zend Technologies Ltd. All rights reserved.</p>-->
<!--            </footer>-->
<!--        </div>-->
<!--        --><?//= $this->inlineScript() ?>
<!--    </body>-->
<!--</html>-->
