<div class="login-logo">
    <p><b>ZF3</b> na prática</p>
</div>
<!-- /.login-logo -->
<div class="login-box-body">
    <p class="login-box-msg">Esqueceu sua senha? Crie uma nova.</p>

    <form action="" method="POST">
        <div class="form-group has-feedback">
            <input type="password" name="password" class="form-control" placeholder="Password" maxlength="48">
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
            <input type="password" name="verifypassword" class="form-control" placeholder="Retype password" maxlength="48">
            <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
        </div>
        <div class="row">
            <div class="pull-right col-xs-4">
                <button type="submit" class="btn btn-primary btn-block btn-flat">Nova senha</button>
            </div>
        </div>
    </form>
    <a href="login.html">Voltar para login</a><br>

</div>
