<div class="login-logo">
    <p><b>ZF3</b> na prática</p>
</div>
<!-- /.login-logo -->
<div class="login-box-body">
    <p class="login-box-msg">Esqueceu sua senha? Crie uma nova.</p>

    <form action="">
        <div class="form-group has-feedback">
            <input type="email" name="email" class="form-control" placeholder="Email">
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
        </div>
        <div class="row">
            <div class="pull-right col-xs-4">
                <button type="submit" class="btn btn-primary btn-block btn-flat">Nova senha</button>
            </div>
        </div>
    </form>

    <a href="<?= $this->url('user/default', ['controller'=>'index', 'action'=>'register']); ?>">Voltar para login</a><br>

</div>
